{{- if .Values.nsqadmin.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "nsq.nsqadmin.fullname" . }}
  labels:
    {{- include "nsq.commonLabels" . | nindent 4 }}
  {{- with .Values.nsqadmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nsqadmin.ingress.tls }}
  tls:
    {{- range .Values.nsqadmin.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.nsqadmin.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "nsq.nsqadmin.fullname" . }}
          servicePort: {{ .Values.nsqadmin.service.port }}
{{- end }}
