{{- if and .Values.nsqd.enabled (ne "headless" .Values.nsqd.service.type) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsq.nsqd.fullname" . }}
  labels:
    {{- include "nsq.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.nsqd.service.type }}
  ports:
  - port: 4151
    targetPort: http
  - protocol: TCP
    port: 4150
    targetPort: tcp
  selector:
    {{- include "nsq.nsqd.selectorLabels" . | nindent 4 }}
{{- end }}