{{- if .Values.applicationServer.enabled -}}
{{- if .Values.applicationServer.ingress.enabled -}}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "chirpstack.fullname" . }}-application-server
  labels:
    app: chirpstack-application-server
  {{- with .Values.applicationServer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.applicationServer.ingress.tls }}
  tls:
    {{- range .Values.applicationServer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: /
        backend:
          serviceName: {{ template "chirpstack.fullname" . }}-application-server
          servicePort: 8080
      {{- else }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "chirpstack.fullname" . }}-application-server
            port:
              number: 8080
      {{- end }}
    {{- if .Values.applicationServer.ingress.host }}
    host: {{ .Values.applicationServer.ingress.host | quote }}
    {{- end }}
{{- end }}
{{- end }}
