{{- if not .Values.mqtt.server -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.name" . }}-mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt
    nodePort: {{ .Values.mosquitto.service.nodePort }}
  type: NodePort
  selector:
    app: mosquitto
{{- end }}

