apiVersion: v1
kind: Service
metadata:
  name: {{ template "chirpstack.fullname" . }}-mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt
  type: NodePort
  selector:
    app: mosquitto

