name: Lint Helm Charts
on:
  pull_request:
  release:
    types:
    - published
    - created
    - edited
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: "3.5.4"
    - name: Lint nsq
      run: helm lint ./beeinventor/nsq
    - name: Lint opendistro-es
      run: helm lint ./beeinventor/opendistro-es
